# Generated by Django 6.0.4 on 2026-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_sx_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
