# Generated by Django 6.0.4 on 2026-05-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_negotiationthread_seller_negotiationthread_status_and_more'),
        ('threads', '0009_threadmessage_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negotiationthread',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='negotiationthread',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_negotiation', to='threads.thread'),
        ),
    ]
