# Generated by Django 6.0.4 on 2026-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_listing_status_alter_negotiationthread_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
