# Generated by Django 6.0.4 on 2026-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_order_quantity_and_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationthread',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
