# Generated by Django 6.0.4 on 2026-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_negotiationthread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationthread',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
    ]
