# Generated by Django 6.0.4 on 2026-06-10 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_negotiationthread_message_delete_purchaserequest'),
        ('threads', '0010_alter_thread_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_order', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_negotiations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='marketplace.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_negotiations', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_order', to='threads.thread')),
            ],
            options={
                'db_table': 'marketplace_negotiationthread',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='NegotiationThread',
        ),
    ]
