# Generated by Django 6.0.4 on 2026-06-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_remove_purchaseorder_is_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={},
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table=None,
        ),
    ]
