# Generated by Django 6.0.4 on 2026-05-23

import django.db.models.deletion
from django.db import migrations, models


PREDEFINED_LOCATIONS = [
    "United International University, Madani Ave, Dhaka",
    "Badda AAMRA Gate",
    "Bashundhara Residential Area",
    "Kuril Bishwa Road",
    "Rampura",
    "Mohakhali",
    "Gulshan 1",
    "Banani",
    "Farmgate",
    "Mirpur 10",
    "Dhanmondi Lake Park",
    "Uttara Sector 10",
]


def seed_locations(apps, schema_editor):
    Location = apps.get_model('ride_share', 'Location')
    RidePost = apps.get_model('ride_share', 'RidePost')

    location_names = set(PREDEFINED_LOCATIONS)

    for ride_post in RidePost.objects.all():
        if ride_post.starting_location:
            location_names.add(ride_post.starting_location)
        if ride_post.destination_location:
            location_names.add(ride_post.destination_location)

    for name in sorted(location_names):
        Location.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0007_alter_ridegroupmember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ridepost',
            name='starting_location',
            field=models.ForeignKey(db_column='starting_location', help_text='Your pickup area or landmark', on_delete=django.db.models.deletion.PROTECT, related_name='ride_posts_as_start', to='ride_share.location'),
        ),
        migrations.AlterField(
            model_name='ridepost',
            name='destination_location',
            field=models.ForeignKey(db_column='destination_location', default='United International University, Madani Ave, Dhaka', on_delete=django.db.models.deletion.PROTECT, related_name='ride_posts_as_destination', to='ride_share.location'),
        ),
    ]
