# Generated by Django 6.0.4 on 2026-05-23

from django.db import migrations


OLD_LOCATION = "United International University, Madani Ave, Dhaka"
NEW_LOCATION = "United International University"


def rename_uiu_location(apps, schema_editor):
    Location = apps.get_model('ride_share', 'Location')
    RidePost = apps.get_model('ride_share', 'RidePost')

    if Location.objects.filter(name=OLD_LOCATION).exists():
        Location.objects.update_or_create(name=NEW_LOCATION, defaults={'is_active': True})
        RidePost.objects.filter(starting_location_id=OLD_LOCATION).update(starting_location_id=NEW_LOCATION)
        RidePost.objects.filter(destination_location_id=OLD_LOCATION).update(destination_location_id=NEW_LOCATION)
        Location.objects.filter(name=OLD_LOCATION).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0008_location_and_ridepost_location_fks'),
    ]

    operations = [
        migrations.RunPython(rename_uiu_location, migrations.RunPython.noop),
    ]