# Generated by Django 6.0.4 on 2026-05-23 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0009_rename_uiu_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridepost',
            name='destination_location',
            field=models.ForeignKey(db_column='destination_location', default='United International University', on_delete=django.db.models.deletion.PROTECT, related_name='ride_posts_as_destination', to='ride_share.location'),
        ),
        migrations.CreateModel(
            name='RideMonitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_university', 'Going to University'), ('to_home', 'Going Home')], default='to_university', max_length=20)),
                ('departure_time', models.DateTimeField(help_text='When you want to travel')),
                ('time_window_minutes', models.PositiveIntegerField(default=120, help_text='How far around the requested time to match rides')),
                ('transport_method', models.CharField(choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('cng', 'CNG'), ('microbus', 'MICROBUS')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('destination_location', models.ForeignKey(db_column='destination_location', default='United International University', on_delete=django.db.models.deletion.PROTECT, related_name='ride_monitor_requests_as_destination', to='ride_share.location')),
                ('starting_location', models.ForeignKey(db_column='starting_location', help_text='Your pickup area or landmark', on_delete=django.db.models.deletion.PROTECT, related_name='ride_monitor_requests_as_start', to='ride_share.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_monitor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RideMonitorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('joined', 'Joined'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_matches', to='ride_share.ridepost')),
                ('monitor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='ride_share.ridemonitorrequest')),
            ],
            options={
                'ordering': ['-matched_at'],
                'unique_together': {('monitor_request', 'ride_post')},
            },
        ),
    ]
