# Generated by Django 6.0.4 on 2026-05-23 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0010_alter_ridepost_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridemonitormatch',
            options={'ordering': ['-match_percentage', '-matched_at']},
        ),
        migrations.AddField(
            model_name='ridemonitormatch',
            name='match_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='ridemonitorrequest',
            name='minimum_match_percent',
            field=models.PositiveSmallIntegerField(default=70, help_text='Minimum percentage required for a ride to count as a match', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
