# Generated by Django 6.0.4 on 2026-05-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0011_alter_ridemonitormatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance_to_uiu',
            field=models.FloatField(blank=True, help_text='Distance to UIU in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
