# Generated by Django 6.0.4 on 2026-05-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0012_location_distance_to_uiu_location_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
