# Generated by Copilot on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0013_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemonitorrequest',
            name='minimum_match_percent',
        ),
        migrations.RemoveField(
            model_name='ridemonitormatch',
            name='match_percentage',
        ),
        migrations.AlterModelOptions(
            name='ridemonitormatch',
            options={'ordering': ['-matched_at']},
        ),
    ]