# Generated by Copilot on 2026-05-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0014_remove_percentage_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='distance_to_uiu',
        ),
    ]