# Generated by Django 6.0.4 on 2026-05-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0015_remove_location_distance_to_uiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemonitorrequest',
            name='departure_time',
            field=models.DateTimeField(blank=True, help_text='When you want to travel', null=True),
        ),
        migrations.AlterField(
            model_name='ridemonitorrequest',
            name='time_window_minutes',
            field=models.PositiveIntegerField(default=35, help_text='How far around the requested time to match rides'),
        ),
        migrations.AlterField(
            model_name='ridemonitorrequest',
            name='transport_method',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('cng', 'CNG'), ('microbus', 'MICROBUS')], max_length=20, null=True),
        ),
    ]
