# Generated by Django 6.0.4 on 2026-05-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_share', '0016_alter_ridemonitorrequest_departure_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridemonitorrequest',
            name='time_window_minutes',
        ),
    ]
