# Generated by Django 6.0.4 on 2026-05-24 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0015_userskill_status_alter_skill_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('language', 'Language'), ('music', 'Music'), ('arts', 'Arts & Design'), ('science', 'Science'), ('sports', 'Sports'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='userskill',
            name='role',
            field=models.CharField(choices=[('teach', 'Can Teach'), ('learn', 'Wants to Learn'), ('both', 'Teach & Learn')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SkillSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='other', max_length=50)),
                ('proficiency_level', models.PositiveSmallIntegerField(default=1)),
                ('proficiency_method', models.CharField(blank=True, max_length=100)),
                ('proficiency_notes', models.TextField(blank=True)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('role', models.CharField(default='both', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderator_note', models.TextField(blank=True, help_text='Reason for rejection — shown to the user')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='skill_exchange.skill')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_skill_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
