# Generated by Django 6.0.4 on 2026-06-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0017_remove_skill_category_alter_userskill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsubmission',
            name='category',
        ),
    ]
