# Generated by Django 6.0.4 on 2026-06-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0018_remove_skillsubmission_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='role',
        ),
        migrations.DeleteModel(
            name='SkillSubmission',
        ),
    ]
