# Generated by Django 6.0.4 on 2026-06-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0009_threadmessage_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
