# Generated by Django 6.0.4 on 2026-05-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_name'),
        ('forum', '0003_remove_forumthread_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.department'),
        ),
    ]
