# Generated by Django 6.0.4 on 2026-05-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_forumthread_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThreadFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('forum_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='forum.forumthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'forum_thread')},
            },
        ),
    ]
