# Generated by Django 6.0.4 on 2026-05-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_forumthreadfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
