# Generated by Django 6.0.4 on 2026-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_forumthread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
