# Generated by Django 6.0.4 on 2026-06-09 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_code_alter_course_name_and_more'),
        ('forum', '0008_alter_forumthread_title'),
        ('threads', '0009_threadmessage_is_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['department', 'course'], name='forum_forum_departm_3508b9_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['author'], name='forum_forum_author__26a0a3_idx'),
        ),
    ]
