# Generated by Django 6.0.4 on 2026-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_forumthread_forum_forum_departm_3508b9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('deleted', 'Deleted')], default='open', max_length=20),
        ),
    ]
